from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_
from sqlalchemy.orm import selectinload
from typing import List
from datetime import datetime, timezone
import uuid

from app.db.session import get_db
from app.core.dependencies import get_current_user, require_role
from app.models.user import User
from app.models.report import MonthlyReport
from app.schemas.report import MonthlyReportResponse, MonthlyReportCreate, MonthlyReportUpdate

router = APIRouter()

@router.get("/", response_model=List[MonthlyReportResponse])
async def get_reports(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    month: str = None,
):
    """
    Get monthly reports.
    - Operators see their own reports.
    - Admins see all reports for their organization.
    """
    stmt = select(MonthlyReport).where(MonthlyReport.organization_id == current_user.organization_id)
    
    if current_user.role == "operator":
        stmt = stmt.where(MonthlyReport.operator_id == current_user.id)
        
    if month:
        stmt = stmt.where(MonthlyReport.month_year == month)
        
    stmt = stmt.order_by(MonthlyReport.created_at.desc())
    result = await db.execute(stmt)
    return result.scalars().all()


@router.post("/", response_model=MonthlyReportResponse)
async def create_report(
    report_in: MonthlyReportCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_role("operator"))
):
    """
    Operator creates a draft monthly report. 
    In production, this could be auto-generated by a Celery task on the 1st of the month,
    but we allow manual creation for testing.
    """
    current_month = datetime.now(timezone.utc).strftime("%Y-%m")
    
    # Check if report already exists for this month
    existing = await db.execute(
        select(MonthlyReport).where(
            MonthlyReport.operator_id == current_user.id,
            MonthlyReport.month_year == current_month
        )
    )
    if existing.scalar_one_or_none():
        raise HTTPException(status_code=400, detail="Report for this month already exists")

    # TODO: Auto-calculate stats (team_size, tasks_completed, etc.)
    new_report = MonthlyReport(
        operator_id=current_user.id,
        organization_id=current_user.organization_id,
        month_year=current_month,
        status="draft",
        achievements=report_in.achievements,
        challenges=report_in.challenges,
        support_needed=report_in.support_needed
    )
    db.add(new_report)
    await db.commit()
    await db.refresh(new_report)
    return new_report


@router.patch("/{report_id}", response_model=MonthlyReportResponse)
async def update_report(
    report_id: uuid.UUID,
    update_in: MonthlyReportUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    result = await db.execute(select(MonthlyReport).where(MonthlyReport.id == report_id))
    report = result.scalar_one_or_none()
    
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
        
    if current_user.role == "operator" and report.operator_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not authorized")
        
    if report.status == "reviewed":
        raise HTTPException(status_code=400, detail="Cannot edit a reviewed report")

    update_data = update_in.model_dump(exclude_unset=True)
    
    # Handle status changes
    if "status" in update_data:
        if update_data["status"] == "submitted" and report.status == "draft":
            report.submitted_at = datetime.now(timezone.utc)
        elif update_data["status"] == "reviewed":
            if current_user.role != "admin":
                raise HTTPException(status_code=403, detail="Only admins can review reports")
            report.reviewed_at = datetime.now(timezone.utc)
            report.reviewed_by = current_user.id

    for key, value in update_data.items():
        setattr(report, key, value)
        
    await db.commit()
    await db.refresh(report)
    return report

