"""add_push_subscriptions_table

Revision ID: 0ddd93605390
Revises: 3afaf2c6582f
Create Date: 2026-04-25 13:08:48.721459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ddd93605390'
down_revision = '3afaf2c6582f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
