"""update_ml_config_fields

Revision ID: 1c27590a12cf
Revises: 0ddd93605390
Create Date: 2026-04-25 13:10:58.277014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c27590a12cf'
down_revision = '0ddd93605390'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_configs', sa.Column('retrain_interval_days', sa.Float(), nullable=True))
    op.add_column('ml_configs', sa.Column('historical_data_weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_configs', 'historical_data_weight')
    op.drop_column('ml_configs', 'retrain_interval_days')
    # ### end Alembic commands ###
