"""Add operator_id to users and monthly_reports table

Revision ID: 7ed32542ae09
Revises: 888e75026860
Create Date: 2026-04-25 19:10:29.005462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ed32542ae09'
down_revision = '888e75026860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monthly_reports_month_year', table_name='monthly_reports')
    op.drop_table('monthly_reports')
    op.add_column('tasks', sa.Column('rejection_note', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('operator_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_operator_id'), 'users', ['operator_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['operator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_operator_id'), table_name='users')
    op.drop_column('users', 'assigned_at')
    op.drop_column('users', 'operator_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'reviewed_at')
    op.drop_column('tasks', 'reviewed_by')
    op.drop_column('tasks', 'rejection_note')
    op.create_table('monthly_reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('operator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('month_year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tasks_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tasks_overdue', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_utilization', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('skill_gaps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('achievements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('challenges', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('support_needed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name='monthly_reports_operator_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='monthly_reports_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='monthly_reports_reviewed_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='monthly_reports_pkey')
    )
    op.create_index('ix_monthly_reports_month_year', 'monthly_reports', ['month_year'], unique=False)
    # ### end Alembic commands ###
