"""add_org_session_timeout

Revision ID: 888e75026860
Revises: 1c27590a12cf
Create Date: 2026-04-25 13:13:50.022656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888e75026860'
down_revision = '1c27590a12cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('session_timeout_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'session_timeout_minutes')
    # ### end Alembic commands ###
