"""Re-add monthly_reports table

Revision ID: c605fa51c5b0
Revises: 7ed32542ae09
Create Date: 2026-04-25 19:12:17.015646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c605fa51c5b0'
down_revision = '7ed32542ae09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
