"""Add org settings and ml config

Revision ID: d42f510839a3
Revises: 
Create Date: 2026-04-23 12:24:18.129474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42f510839a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delay_prediction_enabled', sa.Boolean(), nullable=True),
    sa.Column('shap_explanations_enabled', sa.Boolean(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('auto_rebalance_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_assignment_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('require_mfa', sa.Boolean(), nullable=True),
    sa.Column('allow_public_registration', sa.Boolean(), nullable=True),
    sa.Column('allowed_domains', sa.String(length=255), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_task_id'), 'attachments', ['task_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('subtasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtasks_task_id'), 'subtasks', ['task_id'], unique=False)
    op.create_table('task_watchers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_watchers_task_id'), 'task_watchers', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_watchers_user_id'), 'task_watchers', ['user_id'], unique=False)
    op.add_column('audit_logs', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.add_column('notifications', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('action_url', sa.String(length=500), nullable=True))
    op.add_column('notifications', sa.Column('action_type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('related_entity_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('sla_hours', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('escalation_level', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tasks_is_deleted'), 'tasks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_deleted'), table_name='tasks')
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'is_deleted')
    op.drop_column('tasks', 'escalation_level')
    op.drop_column('tasks', 'sla_hours')
    op.drop_column('tasks', 'organization_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'is_deleted')
    op.drop_column('projects', 'organization_id')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_column('notifications', 'related_entity_id')
    op.drop_column('notifications', 'action_type')
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'organization_id')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'organization_id')
    op.drop_index(op.f('ix_task_watchers_user_id'), table_name='task_watchers')
    op.drop_index(op.f('ix_task_watchers_task_id'), table_name='task_watchers')
    op.drop_table('task_watchers')
    op.drop_index(op.f('ix_subtasks_task_id'), table_name='subtasks')
    op.drop_table('subtasks')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_attachments_task_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('ml_configs')
    # ### end Alembic commands ###
